-- Global configs
require('lsp/on_attach')
-- Individual language LSP configs
require('lsp/bash-ls')
require('lsp/css-ls')
require('lsp/docker-ls')
require('lsp/efm-ls')
require('lsp/go-ls')
require('lsp/html-ls')
require('lsp/javascript-ls')
require('lsp/json-ls')
require('lsp/python-ls')
require('lsp/ruby-ls')
require('lsp/terraform-ls')
require('lsp/yaml-ls')
